import { createApp } from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
import store from "./store";
import "./styles/app.css";
import Avatar from "@/components/appAvatar.vue";
const app = createApp(App);
app.use(store);
app.use(router);
app.component("Avatar", Avatar);
app.mount("#app");
